### PR TITLE
Fix #51: Company filter is checked against hardoded Ruuvi value instead of UART-configured value

### LINKED ISSUE #51: app_uart: Company filter is checked against hardoded Ruuvi value instead of UART-configured value.
Line to fix: https://github.com/ruuvi/ruuvi.gateway_nrf.c/blob/4cf5f55ceb4b3152d72df0f1cae69a9d531cd8fc/src/app_uart.c#L434

### PR DESCRIPTION
**Pull request by TheSomeMan**

### CODE REVIEW

**Comment by ojousima** [comment]
Unit tests need to be updated too. PVS Studio license has gone old, I'll request for a new license. Jenkins doesn't build the request for some reason, I'll take a look. 

Looks good to merge after updating unit tests

**Comment by ojousima** [comment]
Has this patch been tested on hardware yet?

**Comment by ojousima** [comment]
Retest this please

(Triggering Jenkins)

**Review by ojousima — APPROVED** [review]
Thanks

**Comment by TheSomeMan** [comment]
> Has this patch been tested on hardware yet?

Yes, I tested it on the Gateway

**Comment by ojousima** [comment]
Thanks, merged it to get past mandatory Jenkins and PVS checks

**Pull request merged**
